version: '3'
services:
  app:
    image: luobogao/youvcr:latest
    restart: unless-stopped
    volumes:
      - ./download:/YouVCR/download
      - ./config.yaml:/YouVCR/config.yaml
    command: ["python3", "main.py"]
    
